# Admin specfic links
ADMIN_HANDLE = "@kwokyto"

# Bot settings
NUMBER_TO_NOTIFY = 5
NUMBER_TO_BUMP = 5

# Messages sent to the user

INVALID_FORMAT_MESSAGE = "A message of invalid format has been sent."
NO_COMMAND_MESSAGE = "No command detected."
START_MESSAGE = "START_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
IN_QUEUE_MESSAGE = "IN_QUEUE_MESSAGE"
JOIN_SUCCESS_MESSAGE = "JOIN_SUCCESS_MESSAGE"
NOT_IN_QUEUE_MESSAGE = "NOT_IN_QUEUE_MESSAGE"
LEAVE_SUCCESS_MESSAGE = "LEAVE_SUCCESS_MESSAGE"
POSITION_MESSAGE = "POSITION_MESSAGE"
QUEUE_LENGTH_MESSAGE = "QUEUE_LENGTH_MESSAGE"
EMPTY_QUEUE_MESSAGE = "EMPTY_QUEUE_MESSAGE"
NEXT_SUCCESS_MESSAGE = "NEXT_SUCCESS_MESSAGE"
COME_NOW_MESSAGE = "COME_NOW_MESSAGE"
BUMP_SUCCESS_MESSAGE = "BUMP_SUCCESS_MESSAGE"